// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { Button, GroupBox, SpinBox, ComboBox, CheckBox, LineEdit, TabWidget, VerticalBox, HorizontalBox,
    Slider, SpinBox } from "std-widgets.slint";
import { GallerySettings } from "../gallery_settings.slint";
import { Page } from "page.slint";

export component ControlsPage inherits Page {
    title: @tr("Controls");
    description: @tr("This page gives an overview of the default widget set provided by Slint. The widgets are available in different styles native, fluent-(dark/light) and material-(dark/light). The widgets can be imported from \"std-widgets.slint\".");

    GroupBox {
        vertical-stretch: 0;
        title: @tr("Buttons");

        HorizontalLayout {
            spacing: 8px;
            alignment: start;

            Button {
                text: @tr("Regular Button");
                enabled: !GallerySettings.widgets-disabled;
            }

            Button {
                text: @tr("Button with Icon");
                icon: @image-url("../../thumbsup.png");
                enabled: !GallerySettings.widgets-disabled;
            }

            Button {
                checkable: true;
                text: self.checked ? @tr("ON") : @tr("OFF");
                enabled: !GallerySettings.widgets-disabled;
            }
        }
    }

    GroupBox {
        title: @tr("CheckBox - SpinBox - ComboBox");
        vertical-stretch: 0;

        HorizontalBox {
            alignment: start;
            checkbox := CheckBox {
                text: checkbox.checked ? @tr("(checked)") : @tr("(unchecked)");
                checked: true;
                enabled: !GallerySettings.widgets-disabled;
            }


        SpinBox {
            vertical-stretch: 0;
            value: 42;
            enabled: !GallerySettings.widgets-disabled;
        }

            ComboBox {
                model: [@tr("Select Something"), @tr("From this"), @tr("Combobox")];
                enabled: !GallerySettings.widgets-disabled;
            }
        }


    }

    GroupBox {
        title: @tr("LineEdit");
        vertical-stretch: 0;

        LineEdit {
            placeholder-text: @tr("Enter some text");
            enabled: !GallerySettings.widgets-disabled;
        }
    }

    GroupBox {
        title: @tr("Slider");
        vertical-stretch: 0;

        Slider {
            min-width: 160px;
            minimum: -100;
            maximum: 100;
            value: 42;
            enabled: !GallerySettings.widgets-disabled;
        }
    }

    GroupBox {
        title: @tr("TabWidget");

        TabWidget {
            Tab {
                title: @tr("Tab 1");

                VerticalBox {
                    alignment: start;

                    GroupBox {
                        title: @tr("Content of tab 1");

                        HorizontalBox {
                            alignment: start;

                            Button {
                                text: @tr("Click me");
                                enabled: !GallerySettings.widgets-disabled;
                            }
                        }
                    }
                }
            }

            Tab {
                title: @tr("Tab 2");

                VerticalBox {
                    alignment: start;

                    GroupBox {
                        title: @tr("Content of tab 2");

                        VerticalBox {
                            alignment: start;

                            CheckBox {
                                text: @tr("Check me");
                                enabled: !GallerySettings.widgets-disabled;
                            }
                        }
                    }
                }
            }

            Tab {
                title: @tr("Tab 3");

                VerticalBox {
                    Text {
                        text: @tr("Content of tab 3");
                    }
                }
            }
        }
    }
}
